DROP DATABASE IF EXISTS RoomFinder;
CREATE DATABASE RoomFinder;
USE RoomFinder;

DROP TABLE IF EXISTS BUILDING;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS AVAILABILITY;
DROP TABLE IF EXISTS TIME_BLOCK;
DROP TABLE IF EXISTS STUDENT_ROOM;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS RESERVATION;

#---------------------------------------------------------------------------------
